### ISSUE TITLE
Wrong Link redirect for BOSS

### ISSUE THREAD

**Issue by gutsytechster** [fossdelhi/buffet#10]
Within the `Dessert` section of Open source program, the Link for BOSS redirects to [penapps.com](http://pennapps.com/) where IMO it should mean to redirect to https://lab.codingblocks.com/boss.

Let me know If I am forgetting something!

**Comment by InquiridorTechie** [comment]
Thanks, @gutsytechster for pointing out the mistake. I will fix this.
