### ISSUE TITLE
Add Competitive Programming wesites.

### ISSUE THREAD

**Issue by InquiridorTechie** [fossdelhi/buffet#3]
Add competitive programming websites link in the `buffet.md` file.

**Comment by GeekyShacklebolt** [comment]
Hey @InquiridorTechie!
Can you please give us an idea on how many such websites you are willing to add it in the buffet?

**Comment by InquiridorTechie** [comment]
@GeekyShacklebolt
As there is no limit but you can add only the best websites link which helps folks to learn in an easy way and save their time in searching other links.

**Comment by GeekyShacklebolt** [comment]
I have added a [PR](https://github.com/fossdelhi/buffet/pull/6) for this issue. @InquiridorTechie please have a look at the PR and let me know if you want to add more such websites.
