### ISSUE TITLE
Give buffet a directory structure

### ISSUE THREAD

**Issue by GeekyShacklebolt** [fossdelhi/buffet#4]
Just giving a humble suggestion, if we would like to consider giving buffet a directory structure rather than just keeping all the files in the root directory of the repository?
I am suggesting the following initial setup for the project:

--------------------------------------------
- buffet
     - docs
          - CONTRIBUTORS.md
          - How_To_Contribute.md
          - Changelog.md (yet to add)
     - src
         - buffet.md
     - README.md
     - LICENCE
     - index.html (If you want to consider the option of gh-pages)
---------------------------------------------
This is to keep the directory structure expendable and more readable.

**Comment by InquiridorTechie** [comment]
I like this directory structure. But I will not include `index.html` in the root directory. For version 1 I want to keep it purely markdown. Thanks for suggesting this. Do you want to suggest anything? before I ammend these changes.

**Comment by GeekyShacklebolt** [comment]
Not for now, just give directory structure and add a changelog. :)
