### ISSUE TITLE
Make presentation layout like a meal in buffet

### ISSUE THREAD

**Issue by GeekyShacklebolt** [fossdelhi/buffet#8]
Hey @InquiridorTechie

What I thought about the presentation layout of this project is that, since we are making a `buffet` we may categorize techs more creatively like

#### Starters
- How to become a hacker?
- Why to learn early
- Git
- Linux Command Line
etc

#### Main Course
Now you may add all the dishes you want

#### Salad
- CV making websites
- Presentation making websites
etc

We may add such meal stages to give this project a foody look.

**Comment by InquiridorTechie** [comment]
# Buffet

## `Starter:`

- How to become a Hacker?
- Why learn early?
- How to ask a smart question?
- Git 
- Linux command line
- IRC
- Mailing List Etiquettes
- Foss

## `Main Course:`

- ### Programming languages

    - Python3
    - C++
    - C
    - Java
    - C#
    - R 
    - Swift
    - Kotlin
    - Perl
    - Go
    - Haskell
    
- ### Web Development

    ##### 1. Frontend Web Development

    - HTML5
    - CSS
    - Bootstrap4
    - JavaScript
         - Angular
         - React Native     
         - Redux.js
         - Vue.js
         - Web Accessibility
         - Ajax

    ##### 2. Backend Web Development

    - Django - Python
    - Flask - Python
    - Node.JS
    - PHP
    - Ruby
    
- ### Android Development
- ### Data Structures
- ### Version Control

    - **GitHub**
    - **Mercurial**
    
- ### Shell Scripting

- ### Competitive Programming Websites
- ### Database
     - **SQL**
     - **MySQL**
     - **PostgreeSQL**
     - **MongoDB**
     - **Oracle Database**
- ### Artificial Intelligence
- ### Machine Learning
- ### Deep Learning
- ### Docker
- ### IOS Development
- ### IOT
- ### Markup Languages
    - Markdown
    - Latex
    - ReST
- ### Static Website Generator tool
    - Nicola
    - Pelican
    - Jekyll

## `Beverages:`

- ### CV Websites
- ### Presentation making websites
- ### Network Terminology
    - DHCP
    - NAT
    - Subnetting
    - IPv4
    - IPv6
    - Public v Private IP
    - DNS
    - Routers and switches
    - VLANs
    - OSI model
    - MAC addressing
    - ARP
- ### How web works?
- ### Agile Development
- ### Scrum master
- ### Ansible

## `Dessert:`

- ### Free Programming books [download pdf]
- ### Competitive Programming Websites
- ### Interview Tips
- ### Blogs
- ### Open Source Projects

@GeekyShacklebolt what you say about this structure?
